### ISSUE TITLE
Point cloud mirrored in RVIZ

### ISSUE THREAD

**Issue by PaddyCube** [AlessioMorale/ld06_lidar#10]
Hello,

thanks to your work I was able to get lidar up and running. However when observing the point cloud, it is mirrored in RVIZ. Any ideas what's wrong?
I double checked with the Windows program LDROBOT provides and there the point cloud matches real world.

**Comment by AlessioMorale** [comment]
Hi, 
I cherry -picked the fix from https://github.com/linorobot/ldlidar in #13, It's tested and now merged into main.
I'm now looking for a proper way to store the documents without having them in git.
