### ISSUE TITLE
No issue just pure thanks! [compliments to the dev!]

### ISSUE THREAD

**Issue by castaway2000** [AlessioMorale/ld06_lidar#15]
Thanks for making this driver setup. works with noetic as well the only thing we had missing was libudev.h dependencies 

a simple `sudo apt-get install libudev-dev` fixed it. 

We tried three separate drivers before this one worked for us. I appreciate your efforts the big one was the automated device detection and your launch files saved me a lot of headache.

**Comment by AlessioMorale** [comment]
Hi, thanks for your message. 
Actually, there should be no need to install it manually as that should be handled using `rosdep`.
I'm fixing the readme to include the relevant instructions.
