### ISSUE TITLE
Change rotational speed?

### ISSUE THREAD

**Issue by tranqkhue** [AlessioMorale/ld06_lidar#8]
Hello,
I could not find any information on changing the rotational speed of the Lidar, as the document only mentions receiving the data. Do you have any resources on this, or maybe we can ask LDrobot then? 
Many thanks :D

**Comment by AlessioMorale** [comment]
As far as I know, there is no public resource available on this topic. 
I can see that the adapter board provided by LDRobot has a Silab f330 chip on board that I guess it's used to generate the PWM signal to set the rotation speed.
The Lidar module itself has no data input pins besides this motor rotation PWM input pin.
